# This is a config for E2B sandbox template.
# You can use template ID (nzzamo5jrpsuxbx9vtdl) or template name (vib-next-js) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vib-next-js") # Sync sandbox
# sandbox = await AsyncSandbox.create("vib-next-js") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vib-next-js')

team_id = "965b26aa-ca4a-46e1-87cd-630101ae95e8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vib-next-js"
template_id = "nzzamo5jrpsuxbx9vtdl"
